export class ConstantUI {

  static readonly TITLE: number = 24;
  static readonly TEXT: number = 14;
  static readonly BUTTON_FONT: number = 18;
  static readonly VERSION_FONT: number = 12;

  static readonly BUTTON_WIDTH: string = '80%';
  static readonly BUTTON_HEIGHT: number = 48;
  static readonly BUTTON_RADIUS: number = 24;
  static readonly ITEM_RADIUS: number = 12;

  static readonly MARGIN_TOP_HEADER: number = 32;
  static readonly MARGIN_MEDIUM: number = 16;
  static readonly MARGIN_SMALL: number = 8;
  static readonly MARGIN_BOTTOM_HEADER: number = 8;
  static readonly MARGIN_BOTTOM_TAGLINE: number = 32;
  static readonly MARGIN_TOP_LINK: number = 24;
  static readonly MARGIN_BOTTOM_VERSION: number = 5;

  static readonly PADDING_MEDIUM : number = 16;
  static readonly PADDING_SMALL : number = 8;
  static readonly LONG_DURATION : number = 1000;

  static readonly DURATION: number = 150;
  static readonly SCALE_DOWN: number = 0.9;

  static readonly FULL_WIDTH: string = '100%';
  static readonly FULL_HEIGHT: string = '100%';
}
